### ISSUE TITLE
Question: Is it possible to use 2 transitions?

### ISSUE THREAD

**Issue by jwoertink** [sharingapples/react-native-transition#1]
I have a setup where I touch a button, and I use the `SlideLeft` to bring a new page in, but when I close that page, I want it to `SlideRight`. Right now it will also slide left. Is there a way to specify the reverse animation of the one used to bring the new view in?

Right now my thought is to hold that direction in state, then based on the state render a different transition element. My only worry is that when the app first boots, I have no idea which transition should be the default. I will have a slide from the top down (and then back up when done), slide left, slide right (and their opposites), etc...

**Comment by syaau** [comment]
You could pass the transition style in the show method. Have you tried that ?

**Comment by jwoertink** [comment]
I have not. What would I use to instantiate my Transition component if I did that? or do you have an example of what this would look like?

**Comment by syaau** [comment]
https://github.com/sharingapples/react-native-transition#methods

You could call `Transition.show` directly if there is only one transition component, but if you want to target the specific component, you could use `ref` to get reference to the component and then call `show` on that reference.

**Comment by jwoertink** [comment]
I've never used react or react native before so I'm still not quite following. I'm only a hand full of hours in to this thing, but if you're saying it's possible, then that's good enough for me! I'll figure it from here. Thanks for the help.
