### ISSUE TITLE
Cannot read property 'shape' of undefined

### ISSUE THREAD

**Issue by basudz365** [sharingapples/react-native-transition#2]
Looks like this issue is due to the PropTypes being moved into it's own lib?

I'm using react-native 0.46.0, react 16.0.0.-alpha.12
![screenshot_20170906-171844](https://user-images.githubusercontent.com/19153079/30135446-baddb7b0-9328-11e7-855e-988902435b31.png)

**Comment by syaau** [comment]
I just upgraded my demo project to the latest react native (0.48). It worked without an issue. PropTypes show as depreciated but still works. It looks like some other problem.

You can checkout the demo project here, https://github.com/sharingapples/react-native-transition-demo.

**Comment by basudz365** [comment]
Hmm, that's weird.  I went through transitionStylePropType.js and Transition.js and converted to the prop-types lib and everything seems to work now.

Submitted a PR with the PropTypes update.

**Comment by basudz365** [comment]
Closing since this has been fixed in 1.1.8
